on:
  push:
    branches:
      - main

name: Release

jobs:
  linux_arm6:
    name: Create release for Linux ARMv6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-rust@v0
        with:
          targets: 'arm-unknown-linux-gnueabihf'
      - name: Build release binary for Linux ARMv6
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target arm-unknown-linux-gnueabihf --verbose --bin logger
      - name: List Directories and Files
        run: |
          # Install tree if not available
          if ! command -v tree &> /dev/null; then
            apt-get update
            apt-get install -y tree
          fi

          # Print directory and file structure using tree command
          tree
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/arm-unknown-linux-gnueabihf/logger
          asset_name: logger-arm-unknown-linux-gnueabihf
          tag: ${{ steps.tag_version.outputs.new_tag }}
          overwrite: true
